apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: redis-operator
      version: "1.2.0"
      sourceRef:
        kind: HelmRepository
        name: ot-helm
        namespace: flux-system
      interval: 1m
  values:
    redisOperator:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi