apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: redis
      version: "17.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: replication
    sentinel:
      enabled: true
    auth:
      enabled: false
    replica:
      replicaCount: 3
    resources:
      requests:
        cpu: 100m
        memory: 256Mi